// src/lib/data.js

// =========================================================
// 1. DATA AND THEME DEFINITIONS (Example/Truncated)
// You must replace these with your complete objects.
// =========================================================

export const themeStyles = {
  // Example Theme: Replace with your actual theme data
  red: {
    avatarBorder: "#ff2c2c",
    avatarShadow: "0 0 12px #ff2c2c",
    usernameBg: "rgba(255, 0, 0, 0.5)",
    usernameColor: "#fff",
    usernameShadow: "0 1px 4px rgba(255, 0, 0, 0.2)",
    descriptionBg: "rgba(255, 0, 0, 0.3)",
    descriptionColor: "#ccc",
    descriptionShadow: "0 1px 3px rgba(255, 0, 0, 0.1)",
    linkBg: "linear-gradient(to right, #ff1e1e, #9c0b0b)",
    linkHoverBg: "linear-gradient(to right, #ff4c4c, #b81a1a)",
    linkColor: "#fff",
    linkShadow: "0 2px 10px rgba(255, 0, 0, 0.5)",
    linkHoverShadow: "0 4px 15px rgba(255, 0, 0, 0.6)",
    scrollbarThumb: "rgba(255, 0, 0, 0.3)",
    adBg: "#1a0000",
    adShadow: "0 4px 10px rgba(255, 0, 0, 0.3)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  blue: {
    avatarBorder: "#00b4ff",
    avatarShadow: "0 0 12px #00b4ff",
    usernameBg: "rgba(0, 120, 255, 0.5)",
    usernameColor: "#fff",
    usernameShadow: "0 1px 4px rgba(0, 120, 255, 0.3)",
    descriptionBg: "rgba(0, 120, 255, 0.3)",
    descriptionColor: "#cceeff",
    descriptionShadow: "0 1px 3px rgba(0, 120, 255, 0.2)",
    linkBg: "linear-gradient(to right, #007bff, #0052cc)",
    linkHoverBg: "linear-gradient(to right, #3399ff, #0066cc)",
    linkColor: "#fff",
    linkShadow: "0 2px 10px rgba(0, 120, 255, 0.5)",
    linkHoverShadow: "0 4px 15px rgba(0, 120, 255, 0.6)",
    scrollbarThumb: "rgba(0, 120, 255, 0.3)",
    adBg: "#001b2e",
    adShadow: "0 4px 10px rgba(0, 120, 255, 0.3)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  white: {
    avatarBorder: "#ccc",
    avatarShadow: "0 0 10px rgba(0,0,0,0.1)",
    usernameBg: "#f2f2f2",
    usernameColor: "#111",
    usernameShadow: "none",
    descriptionBg: "#f9f9f9",
    descriptionColor: "#333",
    descriptionShadow: "none",
    linkBg: "linear-gradient(to right, #ffffff, #e6e6e6)",
    linkHoverBg: "linear-gradient(to right, #f2f2f2, #dcdcdc)",
    linkColor: "#000",
    linkShadow: "0 2px 6px rgba(0, 0, 0, 0.1)",
    linkHoverShadow: "0 4px 10px rgba(0, 0, 0, 0.15)",
    scrollbarThumb: "rgba(0, 0, 0, 0.2)",
    adBg: "#eeeeee",
    adShadow: "0 4px 10px rgba(0, 0, 0, 0.05)",
    titleShadow: "0 0 3px #fff, 0 0 5px #fff",
  },
  skyblue: {
    avatarBorder: "#87ceeb",
    avatarShadow: "0 0 12px #87ceeb",
    usernameBg: "rgba(135, 206, 235, 0.3)",
    usernameColor: "#003344",
    usernameShadow: "0 1px 4px rgba(135, 206, 235, 0.4)",
    descriptionBg: "rgba(135, 206, 235, 0.2)",
    descriptionColor: "#002222",
    descriptionShadow: "0 1px 3px rgba(135, 206, 235, 0.3)",
    linkBg: "linear-gradient(to right, #87cefa, #00bfff)",
    linkHoverBg: "linear-gradient(to right, #add8e6, #009acd)",
    linkColor: "#002244",
    linkShadow: "0 2px 8px rgba(135, 206, 235, 0.4)",
    linkHoverShadow: "0 4px 12px rgba(135, 206, 235, 0.5)",
    scrollbarThumb: "rgba(135, 206, 235, 0.4)",
    adBg: "#e0f7ff",
    adShadow: "0 4px 10px rgba(135, 206, 235, 0.3)",
    titleShadow: "0 0 3px #fff, 0 0 5px #fff",
  },
  cyan: {
    avatarBorder: "#00ffff",
    avatarShadow: "0 0 12px #00ffff",
    usernameBg: "rgba(0, 255, 255, 0.3)",
    usernameColor: "#ffffff",
    usernameShadow: "0 1px 4px rgba(0, 255, 255, 0.4)",
    descriptionBg: "rgba(0, 255, 255, 0.2)",
    descriptionColor: "#e0ffff",
    descriptionShadow: "0 1px 3px rgba(0, 255, 255, 0.3)",
    linkBg: "linear-gradient(to right, #00ffff, #003333)",
    linkHoverBg: "linear-gradient(to right, #1affff, #005555)",
    linkColor: "#ffffff",
    linkShadow: "0 2px 10px rgba(0, 255, 255, 0.4)",
    linkHoverShadow: "0 4px 15px rgba(0, 255, 255, 0.6)",
    scrollbarThumb: "rgba(0, 255, 255, 0.4)",
    adBg: "#000000",
    adShadow: "0 4px 10px rgba(0, 255, 255, 0.2)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  purple: {
    avatarBorder: "#a020f0",
    avatarShadow: "0 0 12px #a020f0",
    usernameBg: "rgba(160, 32, 240, 0.2)",
    usernameColor: "#ffffff",
    usernameShadow: "0 1px 4px rgba(160, 32, 240, 0.3)",
    descriptionBg: "rgba(160, 32, 240, 0.15)",
    descriptionColor: "#ddd",
    descriptionShadow: "0 1px 3px rgba(160, 32, 240, 0.2)",
    linkBg: "linear-gradient(to right, #a020f0, #3d0066)",
    linkHoverBg: "linear-gradient(to right, #b84dff, #5e00a3)",
    linkColor: "#fff",
    linkShadow: "0 2px 10px rgba(160, 32, 240, 0.4)",
    linkHoverShadow: "0 4px 15px rgba(160, 32, 240, 0.6)",
    scrollbarThumb: "rgba(160, 32, 240, 0.3)",
    adBg: "#1a001f",
    adShadow: "0 4px 10px rgba(160, 32, 240, 0.3)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  greenblack: {
    avatarBorder: "#00cc66",
    avatarShadow: "0 0 12px #00cc66",
    usernameBg: "rgba(0, 204, 102, 0.2)",
    usernameColor: "#ffffff",
    usernameShadow: "0 1px 4px rgba(0, 204, 102, 0.3)",
    descriptionBg: "rgba(0, 204, 102, 0.15)",
    descriptionColor: "#ccffdd",
    descriptionShadow: "0 1px 3px rgba(0, 204, 102, 0.2)",
    linkBg: "linear-gradient(to right, #00cc66, #003300)",
    linkHoverBg: "linear-gradient(to right, #33ff99, #004d00)",
    linkColor: "#fff",
    linkShadow: "0 2px 10px rgba(0, 204, 102, 0.4)",
    linkHoverShadow: "0 4px 15px rgba(0, 204, 102, 0.6)",
    scrollbarThumb: "rgba(0, 204, 102, 0.3)",
    adBg: "#001a0d",
    adShadow: "0 4px 10px rgba(0, 204, 102, 0.3)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  yellowredblackskin: {
    avatarBorder: "#ffc107",
    avatarShadow: "0 0 12px #ffc107",
    usernameBg: "rgba(255, 193, 7, 0.3)",
    usernameColor: "#5c0000",
    usernameShadow: "0 1px 4px rgba(255, 0, 0, 0.3)",
    descriptionBg: "rgba(255, 224, 178, 0.2)",
    descriptionColor: "#402000",
    descriptionShadow: "0 1px 3px rgba(255, 193, 7, 0.2)",
    linkBg: "linear-gradient(to right, #ffc107, #dc3545, #000000)",
    linkHoverBg: "linear-gradient(to right, #ffdd57, #f44336, #111)",
    linkColor: "#fff3e0",
    linkShadow: "0 2px 10px rgba(255, 193, 7, 0.4)",
    linkHoverShadow: "0 4px 15px rgba(255, 0, 0, 0.6)",
    scrollbarThumb: "rgba(255, 0, 0, 0.3)",
    adBg: "#2b0000",
    adShadow: "0 4px 10px rgba(255, 193, 7, 0.3)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  burntSkin: {
    avatarBorder: "#B03722",
    avatarShadow: "0 0 12px #B03722",
    usernameBg: "rgba(255, 247, 221, 0.9)",
    usernameColor: "#1a1a1a",
    usernameShadow: "0 1px 4px rgba(176, 55, 34, 0.15)",
    descriptionBg: "rgba(255, 247, 221, 0.8)",
    descriptionColor: "#2d1a0d",
    descriptionShadow: "0 1px 3px rgba(176, 55, 34, 0.15)",
    linkBg: "linear-gradient(to right, #B03722, #FEF7DD, #000000)",
    linkHoverBg: "linear-gradient(to right, #C7482D, #FFF8DC, #1a1a1a)",
    linkColor: "#1a1a1a",
    linkShadow: "0 2px 10px rgba(176, 55, 34, 0.3)",
    linkHoverShadow: "0 4px 15px rgba(176, 55, 34, 0.4)",
    scrollbarThumb: "rgba(176, 55, 34, 0.3)",
    adBg: "#1a0900",
    adShadow: "0 4px 10px rgba(176, 55, 34, 0.3)",
    titleShadow: "0 0 3px #fff, 0 0 5px #fff",
  },
  yellowwhiteblack: {
    avatarBorder: "#FFD700",
    avatarShadow: "0 0 12px #FFD700",
    usernameBg: "rgba(255, 215, 0, 0.4)",
    usernameColor: "#ffffff",
    usernameShadow: "0 1px 4px rgba(255, 255, 255, 0.3)",
    descriptionBg: "rgba(255, 255, 255, 0.2)",
    descriptionColor: "#dddddd",
    descriptionShadow: "0 1px 3px rgba(0, 0, 0, 0.2)",
    linkBg: "linear-gradient(to right, #FFD700, #ffffff, #000000)",
    linkHoverBg: "linear-gradient(to right, #fff176, #eeeeee, #222222)",
    linkColor: "#000",
    linkShadow: "0 2px 10px rgba(255, 215, 0, 0.3)",
    linkHoverShadow: "0 4px 15px rgba(255, 255, 255, 0.4)",
    scrollbarThumb: "rgba(255, 255, 0, 0.3)",
    adBg: "#0f0f0f",
    adShadow: "0 4px 10px rgba(255, 215, 0, 0.2)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  purpleblack: {
    avatarBorder: "#a020f0",
    avatarShadow: "0 0 12px #a020f0",
    usernameBg: "rgba(160, 32, 240, 0.2)",
    usernameColor: "#f0e6ff",
    usernameShadow: "0 1px 4px rgba(160, 32, 240, 0.25)",
    descriptionBg: "rgba(160, 32, 240, 0.1)",
    descriptionColor: "#d4bfff",
    descriptionShadow: "0 1px 3px rgba(160, 32, 240, 0.15)",
    linkBg: "linear-gradient(to right, #a020f0, #000)",
    linkHoverBg: "linear-gradient(to right, #b84dff, #111)",
    linkColor: "#fff",
    linkShadow: "0 2px 10px rgba(160, 32, 240, 0.3)",
    linkHoverShadow: "0 4px 15px rgba(160, 32, 240, 0.5)",
    scrollbarThumb: "rgba(160, 32, 240, 0.2)",
    adBg: "#120012",
    adShadow: "0 4px 10px rgba(160, 32, 240, 0.2)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  shinyOrangeGrey: {
    avatarBorder: "#FFA500",
    avatarShadow: "0 0 12px #FFA500",
    usernameBg: "rgba(255, 165, 0, 0.3)",
    usernameColor: "#ffffff",
    usernameShadow: "0 1px 4px rgba(255, 165, 0, 0.4)",
    descriptionBg: "rgba(255, 255, 255, 0.1)",
    descriptionColor: "#dddddd",
    descriptionShadow: "0 1px 3px rgba(0, 0, 0, 0.3)",
    linkBg: "linear-gradient(to right, #FFA500, #ffffff, #000000)",
    linkHoverBg: "linear-gradient(to right, #ffcc66, #f5f5f5, #222222)",
    linkColor: "#000000",
    linkShadow: "0 2px 10px rgba(255, 165, 0, 0.3)",
    linkHoverShadow: "0 4px 15px rgba(255, 165, 0, 0.5)",
    scrollbarThumb: "rgba(255, 165, 0, 0.4)",
    adBg: "#1a1a1a",
    adShadow: "0 4px 10px rgba(255, 165, 0, 0.3)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  blackGrey: {
    avatarBorder: "#d0d0d0",
    avatarShadow: "0 0 10px rgba(255, 255, 255, 0.15)",
    usernameBg: "rgba(255, 255, 255, 0.15)",
    usernameColor: "#f0f0f0",
    usernameShadow: "0 1px 3px rgba(0, 0, 0, 0.6)",
    descriptionBg: "rgba(255, 255, 255, 0.1)",
    descriptionColor: "#cccccc",
    descriptionShadow: "0 1px 2px rgba(0, 0, 0, 0.5)",
    linkBg: "linear-gradient(to right, #1a1a1a, #2a2a2a, #1a1a1a)",
    linkHoverBg: "linear-gradient(to right, #2a2a2a, #3a3a3a, #2a2a2a)",
    linkColor: "#eeeeee",
    linkShadow: "0 2px 6px rgba(255, 255, 255, 0.1)",
    linkHoverShadow: "0 4px 10px rgba(255, 255, 255, 0.15)",
    scrollbarThumb: "rgba(255, 255, 255, 0.15)",
    adBg: "#111111",
    adShadow: "0 4px 8px rgba(255, 255, 255, 0.1)",
    titleShadow: "0 0 3px #fff, 0 0 5px #fff",
  },
  redWhiteBlack: {
    avatarBorder: "#ffffff",
    avatarShadow: "0 0 10px rgba(255, 255, 255, 0.6)",
    usernameBg: "rgba(0, 0, 0, 0.7)",
    usernameColor: "#ff4d4d",
    usernameShadow: "0 1px 4px rgba(255, 0, 0, 0.5)",
    descriptionBg: "rgba(0, 0, 0, 0.7)",
    descriptionColor: "#ffffff",
    descriptionShadow: "0 1px 3px rgba(255, 0, 0, 0.4)",
    linkBg: "linear-gradient(to right, #ff0000, #ffffff, #000000)",
    linkHoverBg: "linear-gradient(to right, #ff4d4d, #f0f0f0, #1a1a1a)",
    linkColor: "#000000",
    linkShadow: "0 2px 10px rgba(255, 0, 0, 0.4)",
    linkHoverShadow: "0 4px 15px rgba(255, 0, 0, 0.6)",
    scrollbarThumb: "rgba(255, 0, 0, 0.4)",
    adBg: "#1a1a1a",
    adShadow: "0 4px 10px rgba(255, 255, 255, 0.1)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
  default: {
    avatarBorder: "#ccc",
    avatarShadow: "0 0 10px rgba(0,0,0,0.2)",
    usernameBg: "rgba(50, 50, 50, 0.8)",
    usernameColor: "#fff",
    usernameShadow: "none",
    descriptionBg: "rgba(70, 70, 70, 0.7)",
    descriptionColor: "#ccc",
    descriptionShadow: "none",
    linkBg: "linear-gradient(to right, #555, #333)",
    linkHoverBg: "linear-gradient(to right, #777, #555)",
    linkColor: "#fff",
    linkShadow: "0 2px 5px rgba(0, 0, 0, 0.3)",
    linkHoverShadow: "0 4px 8px rgba(0, 0, 0, 0.4)",
    scrollbarThumb: "rgba(255, 255, 255, 0.2)",
    adBg: "#111111",
    adShadow: "0 4px 8px rgba(0, 0, 0, 0.3)",
    titleShadow: "0 0 3px #000, 0 0 5px #000",
  },
};

export const backgroundToTheme = {
  done: "redWhiteBlack",
  design1: "shinyOrangeGrey",
  design2: "blue",
  design3: "cyan",
  design4: "blackGrey",
  design5: "skyblue",
  design6: "blue",
  design8: "greenblack",
  design9: "yellowredblackskin",
  design10: "white",
  design11: "burntSkin",
  design12: "yellowwhiteblack",
  design13: "purpleblack",
  design14: "red",
};

// FULL DATA ARRAY (OLDEST at index 0 to NEWEST at index N-1)
// https://hanimetv.fun/watch
export const originalData = [
  "/my-mother-the-animation-id-01",
  "/akane-wa-tsumare-somerareru-id-01",
  "/kowaremono-risa-plus-the-animation-id-01",
  "/himawari-wa-yoru-ni-saku-id-01",
  "/dainiji-ura-nyuugaku-shiken-id-01",
  "/ima-made-de-ichiban-yokatta-sex-the-animation-id-01",
  "/ane-wa-yanmama-junyuu-chuu-id-01",
  "/toshoshitsu-no-kanojo-seiso-na-kimi-ga-ochiru-made-the-animation-id-01",
  "/succubu-ist-story-the-animation-id-01",
  "/shoujo-tachi-no-sadism-the-animation-id-01",
  "/sagurare-otome-the-animation-id-01",
  "/kanojo-ga-separate-o-matou-riyuu-id-01",
  "/nier-first-assembly-id-01",
  "/gaki-ni-modotte-yarinaoshi-id-01",
  "/daraku-reijou-the-animation-id-01",
  "/yarichin-kateikyoushi-netori-houkoku-id-01",
  "/boku-ni-sexfriend-ga-dekita-riyuu-id-01",
  "/uchi-no-otouto-maji-de-dekain-dakedo-mi-ni-konai-id-01",
  "/natsuyasumi-ake-no-kanojo-wa-id-01",
  "/hajimete-no-hitozuma-id-01",
  "/shuumatsu-no-harem-id-01",
  "/ijirare-fukushuu-saimin-id-01",
  "/dekichau-made-kon-id-01",
  "/kowaremono-the-animation-id-01",
  "/imaria-id-01",
  "/tooi-kimi-ni-boku-wa-todokanai-id-01",
  "/haritsuke-id-01",
  "/swamp-stamp-anime-edition-id-01",
  "/kyonyuu-elf-oyako-saimin-id-01",
  "/inkou-kyoushi-no-saimin-seikatsu-shidouroku-id-01",
  "/jewelry-the-animation-id-01",
  "/mayoiga-no-oneesan-the-animation-id-01",
  "/isekai-yarisaa-id-01",
  "/boku-dake-no-hentai-kanojo-the-animation-id-01",
  "/rikujoubu-joshi-wa-ore-no-nama-onaho-the-animation-id-01",
  "/mako-chan-kaihatsu-nikki-id-01",
  "/tsuma-netori-3-kairaku-ni-ochita-injiru-kyoushi-tachi-id-01",
  "/green-eyes-ane-kyun-yori-the-animation-id-01",
  "/ajisai-no-chiru-koro-ni-id-01",
  "/toshi-densetsu-series-id-01",
  "/amanee-id-01",
  "/chizuru-chan-kaihatsu-nikki-id-01",
  "/garden-takamine-ke-no-nirinka-the-animation-id-01",
  "/pandemic-id-01",
  "/seika-jogakuin-koutoubu-kounin-sao-oji-san-id-01",
  "/ikoku-na-retro-id-01",
  "/saimin-seishidou-id-01",
  "/kanochi-x-netorare-kazoku-the-animation-id-01",
  "/succubus-yondara-haha-ga-kita-id-01",
  "/isekai-kita-node-sukebe-skill-de-zenryoku-ouka-shiyou-to-omou-the-animation-id-01",
  "/kunoichi-id-01",
  "/jashin-shoukan-inran-kyonyuu-oyako-ikenie-gishiki-id-01",
  "/yariman-fudousan-id-01",
  "/imaizumin-chi-wa-douyara-gal-no-tamariba-ni-natteru-rashii-id-01",
  "/muttsuri-dosukebe-tsuyu-gibo-shimai-no-honshitsu-minuite-sex-sanmai-id-01",
  "/futei-with-the-animation-id-01",
  "/chii-chan-kaihatsu-nikki-id-01",
  "/ane-kyun-id-01",
  "/tsuma-ni-damatte-sokubaikai-ni-ikun-ja-nakatta-id-01",
  "/fuuki-iin-to-fuuzoku-katsudou-id-01",
  "/mama-katsu-midareru-mama-tachi-no-himitsu-id-01",
  "/juvenile-pornography-the-animation-id-01",
  "/maid-san-to-boin-damashii-id-01",
  "/ghosts-of-paradise-id-01",
  "/incha-couple-ga-you-gal-tachi-to-sex-training-suru-hanashi-id-01",
  "/megane-no-megami-id-01",
  "/kyonyuu-onna-senshi-dogeza-saimin-id-01",
  "/koi-maguwai-id-01",
  "/viper-gts-id-01",
  "/seikatsu-shuukan-the-animation-id-01",
  "/maro-no-kanja-wa-gatenkei-id-01",
  "/immoral-game-master-the-animation-id-01",
  "/asa-made-shirudaku-oyakodon-id-01",
  "/inshoku-ou-demar-id-01",
  "/kanojo-x-kanojo-x-kanojo-sanshimai-to-no-dokidoki-kyoudou-seikatsu-id-01",
  "/onii-chan-asa-made-zutto-gyutte-shite-id-01",
  "/no-waifu-no-life-id-01",
  "/sweet-home-h-na-onee-san-wa-suki-desu-ka-id-01",
  "/bitch-na-inane-sama-id-01",
  "/netoshisu-id-01",
  "/iinchou-wa-saimin-appli-wo-shinjiteru-id-01",
  "/master-piece-the-animation-id-01",
  "/sukebe-elf-tanbouki-id-01",
  "/kimi-wa-yasashiku-netorareru-the-animation-id-01",
  "/nudist-beach-ni-shuugaku-ryokou-de-the-animation-id-01",
  "/natsuzuma-id-01",
  "/guilty-hole-id-01",
  "/nosewasure-id-01",
  "/sleepless-a-midsummer-nights-dream-the-animation-id-01",
  "/kyonyuu-princess-saimin-id-01",
  "/nonohara-yuzuka-no-himitsu-no-haishin-id-01",
  "/kemonokko-tsuushin-the-animation-id-01",
  "/soredemo-tsuma-wo-aishiteru-2-id-01",
  "/shikijou-kyoudan-id-01",
  "/isekai-harem-monogatari-id-01",
  "/netorareta-bakunyuu-tsuma-tachi-id-01",
  "/itadaki-seieki-id-01",
  "/tonari-no-kanojo-id-01",
  "/tsuma-ga-kirei-ni-natta-wake-id-01",
  "/doukyuusei-remake-the-animation-id-01",
  "/daisuki-na-haha-id-01",
  "/mama-x-holic-miwaku-no-mama-to-amaama-kankei-the-animation-id-01",
  "/kyou-wa-yubiwa-wo-hazusu-kara-id-01",
  "/tokubetsu-jugyou-3-slg-the-animation-id-01",
  "/netokano-id-01",
  "/jk-fuuzoku-gakuensai-id-01",
  "/ano-danchi-no-tsuma-tachi-wa-the-animation-id-01",
  "/boku-wa-chiisana-succubus-no-shimobe-id-01",
  "/nukitashi-the-animation-id-01",
  "/kuro-gal-a-la-carte-id-01",
  "/akogare-no-onna-joushi-ga-aibeya-shucchou-no-tonari-no-bed-de-zetsurin-otoko-ni-netorarete-iru-id-01",
  "/harem-camp-id-01",
  "/eroge-de-subete-wa-kaiketsu-dekiru-the-animation-id-01",
  "/otaku-ni-yasashii-gal-toka-kyonyuu-no-osananajimi-toka-id-01",
  "/midareuchi-id-01",
  "/iribitari-gal-ni-manko-tsukawasete-morau-hanashi-id-01",
  "/joshi-luck-id-01",
  "/nikuen-id-01",
  "/katei-kyoushi-x-saimin-2-the-animation-id-01",
  "/youkoso-sukebe-elf-no-mori-e-id-01",
  "/implicity-id-01",
  "/zoku-oujo-onna-kishi-w-do-gehin-roshutsu-chijoku-no-misemono-dorei-id-01",
  "/furueru-kuchibiru-id-01",
  "/pinkerton-id-01",
  "/tsuma-netori-kan-bijutsu-kyoushi-no-baai-id-01",
  "/imouto-bitch-ni-shiboraretai-id-01",
  "/kazoku-haha-to-shimai-no-kyousei-id-01",
  "/kansen-ball-buster-the-animation-id-01",
  "/suketto-sanjou-the-animation-id-01",
  "/seiyoku-tsuyotsuyo-the-animation-id-01",
  "/hitozuma-no-kuchibiru-wa-kan-chuuhai-no-aji-ga-shite-id-01",
  "/lover-in-law-id-01",
  "/jitaku-keibiin-2019-id-01",
  "/nee-shiyo-id-01",
  "/yumemiru-otome-id-01",
  "/onaho-kyoushitsu-joshi-zenin-ninshin-keikaku-the-animation-id-01",
  "/houkago-initiation-id-01",
  "/kyonyuu-daikazoku-saimin-id-01",
  "/bonyuu-chan-wa-dashitai-id-01",
  "/aisei-tenshi-love-mary-akusei-jutai-the-animation-id-01",
  "/gobaku-moe-mama-tsurezure-id-01",
  "/3piece-the-animation-id-01",
  "/tsuma-wo-dousoukai-ni-ikasetara-id-01",
  "/maid-kyouiku-botsuraku-kizoku-rurikawa-tsubaki-the-animation-id-01",
  "/shihai-no-kyoudan-id-01",
  "/mou-hasamazu-ni-wa-irarenai-hoshi-ni-onegai-shitara-konnani-okkiku-nacchatta-id-01",
  "/natsu-ga-owaru-made-the-animation-id-01",
  "/aoharu-snatch-id-01",
  "/ikusei-id-01",
  "/boku-dake-no-hentai-kanojo-motto-the-animation-id-01",
  "/saimin-jutsu-zero-id-01",
  "/otome-hime-id-01",
  "/kisaku-reiwa-edition-id-01",
  "/katainaka-ni-totsui-de-kita-russia-musume-to-h-shimakuru-ohanashi-id-01",
  "/jitaku-keibiin-2-id-01",
  "/kyonyuu-onna-shikan-sennou-saimin-id-01",
  "/sister-breeder-id-01",
  "/himekishi-olivia-id-01",
  "/iizuka-senpai-x-blazer-ane-kyun-yori-the-animation-id-01",
  "/nightmare-x-deathscythe-hangyaku-no-resonance-id-01",
  "/ano-ko-no-kawari-ni-suki-na-dake-id-01",
  "/hatsukoi-jikan-id-01",
  "/imouto-paradise-3-the-animation-id-01",
  "/tsuma-netori-ryoujoku-rinne-id-01",
  "/my-classmates-mother-id-01",
  "/toilet-no-hanako-san-vs-kukkyou-taimashi-id-01",
  "/yue-ni-hitozuma-wa-netorareta-id-01",
  "/imouto-to-sono-yuujin-ga-ero-sugite-ore-no-kokan-ga-yabai-id-01",
  "/tsurupeta-shugo-kishi-elfina-ochiru-id-01",
  "/class-de-otoko-wa-boku-ichinin-id-01",
  "/houkago-no-yuutousei-id-01",
  "/tanetsuke-oji-san-to-ntr-hitozuma-sex-the-animation-id-01",
  "/netorare-fighter-yaricchingu-id-01",
  "/enjo-kouhai-assisted-mating-id-01",
  "/renseijutsushi-colette-no-h-na-sakusei-monogatari-id-01",
  "/kanojo-ga-nekomimi-ni-kigaetara-id-01",
  "/tsugunai-id-01",
  "/meikoku-gakuen-jutai-hen-id-01",
  "/kuroinu-ii-the-animation-id-01",
  "/mebuki-the-animation-id-01",
  "/toromitsu-musume-no-hitou-service-torottoro-churu-churu-gohoushi-sasete-kudasai-2025-id-01",
  "/konbini-shoujo-z-id-01",
  "/chikan-no-licence-id-01",
  "/imakara-atashi-id-01",
  "/yuusha-hime-miria-id-01",
  "/kyonyuu-reijou-mc-gakuen-id-01",
  "/aku-no-onna-kanbu-full-moon-night-r-id-01",
  "/chijoku-no-seifuku-id-01",
  "/okusama-no-kaifuku-jutsu-the-animation-id-01",
  "/koumi-jima-shuu-7-de-umeru-mesu-tachi-id-01",
  "/hatsujou-switch-otosareta-shoujo-tachi-the-animation-id-01",
  "/baku-ane-2-otouto-ippai-shibocchau-zo-the-animation-id-01",
  "/tanetsuke-oji-san-to-papakko-jd-saimin-seikatsu-the-animation-id-01",
  "/yuugao-id-01",
  "/oni-chichi-harem-id-01",
  "/shachiku-cinderella-id-01",
  "/princess-burst-id-01",
  "/kaa-chan-no-tomodachi-ni-shikotteru-tokoro-mirareta-the-animation-id-01",
  "/tenioha-2-limit-over-mada-mada-ippai-ecchi-shiyo-the-animation-id-01",
  "/yarimoku-beach-ni-shuugakuryokou-de-the-animation-id-01",
  "/niplheim-no-karyuudo-id-01",
  "/subarashiki-kokka-no-kizukikata-id-01",
  "/tsundero-id-01",
  "/s-ke-ni-totsuida-m-jou-no-nichijou-id-01",
  "/kanojo-wa-dare-to-demo-sex-suru-id-01",
  "/meltys-quest-id-01",
  "/boku-ni-harem-sexfriend-ga-dekita-riyuu-id-01",
  "/zoku-tsuma-netori-ikumi-to-shizuka-id-01",
  "/tamashii-insert-id-01",
  "/first-love-id-01",
  "/bitch-gakuen-ga-seijun-na-hazu-ga-nai-the-animation-id-01",
  "/kozukuri-ninkatsu-bu-id-01",
  "/the-hills-have-size-id-01",
  "/gibo-no-toiki-haitoku-kokoro-ni-tadayou-haha-no-iroka-id-01",
  "/saint-dorei-gakuen-2-id-01",
  "/runes-pharmacy-tiarajima-no-okusuriya-san-id-01",
  "/torokase-orgasm-the-animation-id-01",
  "/shoujo-kyouiku-re-id-01",
  "/oujo-onna-kishi-w-do-gehin-roshutsu-id-01",
  "/musuko-no-tomodachi-ni-okasarete-id-01",
  "/tsuma-no-haha-sayuri-id-01",
  "/dearest-blue-id-01",
  "/tsumamigui-3-the-animation-id-01",
  "/sexfriend-gakuen-id-01",
  "/zutto-suki-datta-id-01",
  "/immoral-routine-the-animation-id-01",
  "/taboo-charming-mother-id-01",
  "/sex-friend-osananajimi-shojo-to-doutei-wa-hazukashii-tte-minna-ga-iu-kara-the-animation-id-01",
  "/kyonyuu-jk-ga-ojisan-chinpo-to-jupo-jupo-iyarashii-sex-shitemasu-id-01",
  "/shikkoku-no-shaga-the-animation-id-01",
  "/overflow-id-01",
  "/konna-ni-yasashiku-sareta-no-id-01",
  "/raikou-shinki-aigis-magia-pandra-saga-3rd-ignition-the-animation-id-01",
  "/kakushi-dere-id-01",
  "/mama-puri-id-01",
  "/jk-genkai-koubi-goui-sounyuu-de-bachibachi-niku-anaka-id-01",
  "/soukou-seiki-ysphere-ingyaku-no-sennou-kaizou-id-01",
  "/tsuma-netori-rei-boku-no-ayamachi-kanojo-no-sentaku-id-01",
  "/mesudachi-the-animation-id-01",
  "/youma-shoukan-e-youkoso-id-01",
  "/dokidoki-little-ooyasan-id-01",
  "/aniki-no-yome-san-nara-ore-ni-hamerarete-hiihii-itteru-tokoro-da-yo-id-01",
  "/sakuramiya-shimai-no-netorare-kiroku-id-01",
  "/ikumonogakari-the-animation-id-01",
  "/tenioha-2-nee-motto-ecchi-na-koto-ippai-shiyo-the-animation-id-01",
  "/nariyuki%e2%86%92papakatsu-girls-the-animation-id-01",
  "/succubus-stayed-life-the-animation-id-01",
  "/wife-with-wife-id-01",
  "/iinari-saimin-kanojo-id-01",
  "/sweet-and-hot-id-01",
  "/amai-ijiwaru-id-01",
  "/kyonyuu-hitozuma-onna-kyoushi-saimin-id-01",
  "/shiranai-koto-shiritai-no-the-animation-id-01",
  "/motokare-to-wa-dekinakatta-sex-shitemo-ii-desu-ka-id-01",
  "/gogo-no-kouchou-junai-mellow-yori-id-01",
  "/succubus-appli-gakuen-saimin-id-01",
  "/taimanin-shiranui-inyoku-no-dorei-shoufu-id-01",
  "/kutsujoku-id-01",
  "/futa-bu-id-01",
  "/harem-cult-id-01",
  "/seikatsu-shidou-anime-edition-id-01",
  "/taimanin-asagi-3-id-01",
  "/otome-dori-id-01",
  "/oneshota-the-animation-id-01",
  "/tsuma-ga-onsen-de-circle-nakama-no-nikubenki-ni-natta-no-desu-ga-id-01",
  "/chikan-shita-id-01",
  "/baku-ane-otouto-shibocchau-zo-the-animation-id-01",
  "/netorare-zuma-id-01",
  "/rennyuu-order-the-animation-id-01",
  "/mesu-saga-persona-id-01",
  "/tonari-no-ie-no-anette-san-the-animation-id-01",
  "/muma-no-machi-cornelica-id-01",
  "/furyou-ni-hamerarete-jusei-suru-kyonyuu-okaasan-the-animation-id-01",
  "/ochi-mono-rpg-seikishi-luvilias-id-01",
  "/kichiku-haha-shimai-choukyou-nikki-id-01",
  "/natural-vacation-the-animation-id-01",
  "/ano-ko-to-ii-koto-id-01",
  "/kedamono-tachi-no-sumu-ie-de-id-01",
  "/majuu-jouka-shoujo-utea-id-01",
  "/watashi-wa-kairaku-izonshou-id-01",
  "/sex-ga-suki-de-suki-de-daisuki-na-classmate-no-ano-musume-id-01",
  "/dropout-id-01",
  "/kyonyuu-kazoku-saimin-id-01",
  "/mujin-eki-the-animation-id-01",
  "/toriko-no-shizuku-natsu-no-gouka-kyakusen-de-kegasareru-otome-tachi-id-01",
  "/otogibanashi-no-onigokko-id-01",
  "/ojisan-de-umeru-ana-the-animation-id-01",
  "/mamahaha-id-01",
  "/jitaku-keibiin-id-01",
  "/ana-no-oku-no-ii-tokoro-id-01",
  "/okusama-wa-moto-yariman-id-01",
  "/baka-na-imouto-wo-rikou-ni-suru-no-wa-ore-no-xx-dake-na-ken-ni-tsuite-id-01",
  "/ane-yome-quartet-id-01",
  "/h-na-gishi-series-the-animation-id-01",
  "/shishunki-sex-id-01",
  "/saimin-jutsu-2-id-01",
  "/fukai-ni-nemuru-oujo-no-abaddon-the-animation-id-01",
  "/sexual-pursuit-2-id-01",
  "/shiny-days-id-01",
  "/ikuiku-succubus-saikyouiku-id-01",
  "/donburi-kazoku-id-01",
  "/toumei-ningen-r-id-01",
  "/shiiku-x-kanojo-tenshi-no-kousoku-hen-id-01",
  "/yakata-kannou-kitan-id-01",
  "/rina-to-ana-id-01",
  "/junjou-shoujo-et-cetera-id-01",
  "/inmou-id-01",
  "/fleur-the-animation-id-01",
  "/kunoichi-ryoujokuden-ajisai-id-01",
  "/goblin-no-suana-id-01",
  "/love-x-holic-miwaku-no-otome-to-hakudaku-kankei-the-animation-id-01",
  "/eroriman-2-id-01",
  "/notto-sexaroid-eurie-id-01",
  "/oshikake-bakunyuu-gal-harem-seikatsu-id-01",
  "/resort-boin-id-01",
  "/bible-black-new-testament-id-01",
  "/niizuma-koyomi-the-animation-id-01",
  "/sakusei-byoutou-the-animation-id-01",
  "/jk-bitch-ni-shiboraretai-id-01",
  "/babuka-gokudou-no-tsuma-id-01",
  "/mistreated-bride-id-01",
  "/mankitsu-happening-id-01",
  "/mesu-kyoushi-injoku-no-kyoushitsu-id-01",
  "/love-bitch-yasashii-onna-id-01",
  "/ikkyuu-nyuukon-id-01",
  "/gyakuten-majo-saiban-chijo-na-majo-ni-sabakarechau-the-animation-id-01",
  "/hajimete-no-orusuban-2025-id-01",
  "/pure-pure-pero-pero-princess-id-01",
  "/residence-id-01",
  "/kanojo-ga-yatsu-ni-idakareta-hi-id-01",
  "/shoujo-kyouiku-id-01",
  "/valkyrie-hazard-id-01",
  "/yamitsuki-mura-melty-limit-the-animation-id-01",
  "/oni-chichi-refresh-id-01",
  "/3ping-lovers-ippu-nisai-no-sekai-e-youkoso-the-animation-id-01",
  "/kutsujoku-2-the-animation-id-01",
  "/nuresuke-jk-amayadori-rape-id-01",
  "/ura-jutaijima-id-01",
  "/inyouchuu-etsu-id-01",
  "/bubble-de-house-de-marumarumaru-the-animation-id-01",
  "/real-eroge-situation-2-the-animation-id-01",
  "/kono-koi-ni-kizuite-the-animation-id-01",
  "/choro-mesu-days-id-01",
  "/natsu-ga-owaru-made-natsu-no-owari-the-animation-id-01",
  "/bishoku-ke-no-rule-id-01",
  "/wife-swap-diaries-id-01",
  "/tiny-evil-id-01",
  "/majo-wa-kekkyoku-sono-kyaku-to-the-animation-id-01",
  "/oshioki-gakuen-reijou-kousei-keikaku-id-01",
  "/soredemo-tsuma-wo-aishiteru-id-01",
  "/hitozuma-life-one-time-gal-prequel-id-01",
  "/hime-sama-love-life-id-01",
  "/chichiiro-toiki-id-01",
  "/kuroinu-kedakaki-seijo-wa-hakudaku-ni-somaru-id-01",
  "/oppai-no-ouja-48-id-01",
  "/real-eroge-situation-the-animation-id-01",
  "/toriko-no-kusari-shojo-tachi-wo-yogosu-midara-na-kusabi-id-01",
  "/shunka-shuutou-id-01",
  "/stepmothers-sin-id-01",
  "/kyokugen-chikan-tokuiten-3-the-animation-id-01",
  "/modaete-yo-adam-kun-id-01",
  "/kimi-omou-koi-id-01",
  "/m-ogui-last-order-id-01",
  "/ryuudouji-shimon-no-inbou-id-01",
  "/kangoku-injoku-no-jikkentou-id-01",
  "/papa-katsu-id-01",
  "/69-itsuwari-no-bishou-id-01",
  "/knight-of-erin-id-01",
  "/boku-to-misaki-sensei-id-01",
  "/garden-the-animation-id-01",
  "/gakuen-saimin-reido-id-01",
  "/konomi-ja-nai-kedo-mukatsuku-ane-to-aishou-batsugun-ecchi-id-01",
  "/a-size-classmate-2025-id-01",
  "/boku-to-sensei-to-tomodachi-no-mama-id-01",
  "/jutaijima-id-01",
  "/uhou-renka-id-01",
  "/taimanin-asagi-toraware-no-niku-ningyou-id-01",
  "/rinkan-biyaku-chuudoku-id-01",
  "/cherry-gals-id-01",
  "/hitozuma-mitsu-to-niku-id-01",
  "/yari-agari-id-01",
  "/glass-the-movie-id-01",
  "/soshite-watashi-wa-sensei-ni-id-01",
  "/saimin-gakuen-id-01",
  "/jk-to-ero-konbini-tenchou-id-01",
  "/kakurenbo-the-animation-id-01",
  "/rance-01-hikari-wo-motomete-the-animation-id-01",
  "/gakuen-de-jikan-yo-tomare-id-01",
  "/ushichichi-tabehoudai-the-animation-id-01",
  "/boku-no-risou-no-isekai-seikatsu-id-01",
  "/honoo-no-haramase-oppai-ero-appli-gakuen-the-animation-id-01",
  "/sansha-mendan-rensa-suru-chijoku-choukyou-no-gakuen-id-01",
  "/fella-pure-mitarashi-san-chi-no-jijou-the-animation-id-01",
  "/enkou-jk-bitch-gal-ojisan-to-namapako-seikatsu-id-01",
  "/bijukubo-id-01",
  "/kowaremono-risa-the-animation-id-01",
  "/dokidoki-oyako-lesson-oshiete-h-na-obenkyou-id-01",
  "/koakuma-kanojo-the-animation-id-01",
  "/mashou-no-nie-3-id-01",
  "/hinagiku-virgin-lost-club-e-youkoso-id-01",
  "/rape-gouhouka-id-01",
  "/kanpeki-ojousama-no-watakushi-ga-dogeza-de-mazo-ochisuru-choroin-na-wakenai-desu-wa-id-01",
  "/boy-meets-harem-the-animation-id-01",
  "/koinaka-koinaka-de-hatsukoi-x-nakadashi-sexual-life-the-animation-id-01",
  "/aniyome-id-01",
  "/onna-maou-melissa-no-h-na-boukenki-id-01",
  "/himitsu-no-kichi-id-01",
  "/muchi-muchi-kyosei-seicho-ata-id-01",
  "/mother-knows-breast-id-01",
  "/koutetsu-no-majo-annerose-id-01",
  "/uwaki-to-honki-the-animation-id-01",
  "/summer-inaka-no-seikatsu-id-01",
  "/eroriman-junjou-meikko-o-loveho-ni-tsurekonde-yaritai-houdai-id-01",
  "/ero-ishi-seijun-bishoujo-wo-kotoba-takumi-ni-hametai-houdai-id-01",
  "/ane-chijo-max-heart-id-01",
  "/peropero-teacher-id-01",
  "/after-class-lesson-id-01",
  "/oni-chichi-re-birth-id-01",
  "/1ldk-jk-ikinari-doukyo-micchaku-hatsu-ecchi-id-01",
  "/inbo-id-01",
  "/ane-jiyoku-tsukushi-nee-san-no-shitagi-id-01",
  "/bomb-milk-sisters-id-01",
  "/ichigo-chocolat-flavor-id-01",
  "/tonys-heroine-series-kanojo-wa-hanayome-kouhosei-cinderella-collection-id-01",
  "/aibeya-the-animation-id-01",
  "/soushi-souai-junai-mellow-yori-id-01",
  "/gakuen-3-id-01",
  "/lilitales-id-01",
  "/saimin-gakuen-hypnolove-id-01",
  "/tsuma-shibori-id-01",
  "/hachishaku-hachiwa-keraku-meguri-igyou-kaikitan-the-animation-id-01",
  "/unsweet-netorare-ochita-onna-tachi-id-01",
  "/cleavage-id-01",
  "/anata-wa-watashi-no-mono-do-s-kanojo-to-do-m-kareshi-id-01",
  "/seiso-de-majime-na-kanojo-ga-saikyou-yaricir-ni-kanyuu-saretara-the-animation-id-01",
  "/saimin-class-joshi-zenin-shiranai-uchi-ni-ninshin-shitemashita-id-01",
  "/chiisana-tsubomi-no-sono-oku-ni-id-01",
  "/oniisan-ohitori-desu-ka-id-01",
  "/nozoki-kanojo-id-01",
  "/papa-love-papa-to-icha-ero-shitai-musume-tachi-to-hitotsu-yane-no-shita-de-id-01",
  "/futa-bu-mix-futanari-world-id-01",
  "/abandon-100-nuki-shinai-to-derarenai-fushigi-na-kyoushitsu-id-01",
  "/netoraserare-id-01",
  "/step-milf-id-01",
  "/ito-wo-yoru-id-01",
  "/koushoku-no-chuugi-kunoichi-botan-id-01",
  "/ienai-koto-the-animation-id-01",
  "/sotsugyou-xx-densha-id-01",
  "/genkaku-cool-na-sensei-ga-aheboteochi-id-01",
  "/jiburiru-the-devil-angel-2-id-01",
  "/jinkou-shoujo-henshin-sex-android-id-01",
  "/heartful-maman-the-animation-id-01",
  "/shigokare-ecchi-na-joshi-daisei-to-doki-x2-love-lesson-the-animation-id-01",
  "/kunoichi-botan-id-01",
  "/kininaru-kimochi-id-01",
  "/jukujo-shigan-id-01",
  "/shikoyaka-naru-toki-mo-hameru-toki-mo-id-01",
  "/milf-mansion-id-01",
  "/roshutsu-kei-mahou-joshi-daisei-christhea-id-01",
  "/white-blue-id-01",
  "/yama-hime-no-mi-id-01",
  "/milk-junkie-shimai-hen-id-01",
  "/ore-ga-kanojo-wo-okasu-wake-id-01",
  "/ecchi-na-onee-chan-ni-shiboraretai-id-01",
  "/kyouiku-shidou-the-animation-id-01",
  "/bakunyuu-oyako-id-01",
  "/sexual-pursuit-id-01",
  "/watashi-ga-toriko-ni-natte-yaru-id-01",
  "/jokuana-id-01",
  "/mazome-soap-de-aimashou-id-01",
  "/dorei-nikki-id-01",
  "/buta-no-gotoki-id-01",
  "/issho-ni-h-shiyo-id-01",
  "/ijoku-id-01",
  "/nama-lo-re-furachimono-the-animation-2025-id-01",
  "/soukan-rensa-secret-sex-stories-id-01",
  "/mokkai-shiyo-id-01",
  "/rasen-sokou-no-dystopia-id-01",
  "/soikano-gyutto-dakishimete-the-animation-id-01",
  "/aneimo-square-sisters-id-01",
  "/misuzu-ikenai-koto-id-01",
  "/yamitsuki-pheromone-the-animation-id-01",
  "/imako-system-id-01",
  "/boku-no-yayoi-san-id-01",
  "/kimi-no-mana-wa-rina-witch-id-01",
  "/idol-kyousei-sousa-id-01",
  "/kansen-sodom-id-01",
  "/immoral-wife-insatiable-id-01",
  "/hitou-meguri-kakure-yu-mao-hen-id-01",
  "/makai-kishi-ingrid-re-mesu-buta-dorei-ni-ochita-makai-kishi-id-01",
  "/bust-to-bust-chichi-wa-chichi-ni-id-01",
  "/bible-black-only-version-id-01",
  "/aneki-my-sweet-elder-sister-the-animation-id-01",
  "/shidoukan-day-after-the-animation-id-01",
  "/shoujo-ramune-2025-id-01",
  "/himekishi-angelica-id-01",
  "/kyonyuu-dosukebe-gakuen-id-01",
  "/karada-de-kaiketsu-hyakkiya-tantei-jimusho-id-01",
  "/horny-girl-id-01",
  "/reika-wa-karei-na-boku-no-joou-the-animation-id-01",
  "/hametsu-no-yuuwaku-id-01",
  "/vampire-id-01",
  "/sensual-adventures-id-01",
  "/hissatsu-chikan-nin-id-01",
  "/kazama-mana-id-01",
  "/i-pass-a-baton-to-rena-senpai-id-01",
  "/shikiyoku-infinite-id-01",
  "/kowaku-no-toki-id-01",
  "/waisetsu-missile-the-animation-id-01",
  "/mrs-junkie-id-01",
  "/requiem-anal-sanctuary-id-01",
  "/panchira-teacher-id-01",
  "/rinkan-club-id-01",
  "/mahou-touki-lilustear-id-01",
  "/kono-kaisha-nanika-okashii-id-01",
  "/mofukuzuma-id-01",
  "/oideyo-shiritsu-yarimari-gakuen-id-01",
  "/cele-kano-id-01",
  "/booby-life-id-01",
  "/honoo-no-haramase-doukyuusei-id-01",
  "/fushigi-no-kuni-no-succubus-id-01",
  "/elf-ni-inmon-wo-tsukeru-hon-the-animation-id-01",
  "/euphoria-id-01",
  "/renai-fuyou-gakuha-the-animation-id-01",
  "/kime-koi-takane-no-hana-to-osananajimi-ga-kimatta-riyuu-id-01",
  "/ecchi-na-shintai-sokutei-anime-edition-2025-id-01",
  "/yuutousei-ayaka-no-uraomote-id-01",
  "/baka-dakedo-chinchin-shaburu-no-dake-wa-jouzu-na-chii-chan-id-01",
  "/shimaizuma-shimaizuma-3-the-animation-id-01",
  "/enbi-id-01",
  "/humiliated-wives-id-01",
  "/kagachi-sama-onagusame-tatematsurimasu-netorare-mura-inya-hanashi-the-animation-id-01",
  "/ta-teacher-id-01",
  "/dirty-by-the-dozen-id-01",
  "/haitoku-no-kyoukai-id-01",
  "/wagaya-no-liliana-san-the-animation-id-01",
  "/bible-black-id-01",
  "/junjou-decamelon-id-01",
  "/doctor-shameless-id-01",
  "/hhh-triple-ecchi-id-01",
  "/sleepless-nocturne-the-animation-id-01",
  "/ma-ga-ochiru-yoru-id-01",
  "/bikyaku-seido-kaichou-ai-id-01",
  "/shin-hitou-meguri-id-01",
  "/anette-san-to-liliana-san-the-animation-id-01",
  "/kuro-no-kyoushitsu-id-01",
  "/study-a-broad-id-01",
  "/eroge-h-mo-game-mo-kaihatsu-zanmai-id-01",
  "/boku-to-joi-no-shinsatsu-nisshi-the-animation-id-01",
  "/study-a-broad-2-id-01",
  "/ero-manga-h-mo-manga-mo-step-up-id-01",
  "/onmyouji-ayakashi-no-megami-inran-jubaku-id-01",
  "/night-shift-nurses-experiment-id-01",
  "/kiniitta-chitsu-ni-ikinari-nakadashi-ok-na-resort-tou-id-01",
  "/megachu-id-01",
  "/seikon-no-aria-id-01",
  "/menage-a-twins-id-01",
  "/g-spot-express-id-01",
  "/starless-21st-century-nymphomaniacs-id-01",
  "/ajin-ga-osuki-nan-desu-ne-id-01",
  "/bokura-no-sex-id-01",
  "/jk-to-inkou-kyoushi-4-feat-ero-giin-sensei-id-01",
  "/after-the-animation-id-01",
  "/enyoku-id-01",
  "/nama-lo-re-namakemono-the-animation-2025-id-01",
  "/oyomesama-honey-days-id-01",
  "/aoi-has-an-ecchi-job-at-a-bookstore-id-01",
  "/shakuen-no-eris-id-01",
  "/queen-meets-orc-id-01",
  "/pretty-x-cation-2-the-animation-id-01",
  "/honey-blonde-2-id-01",
  "/wanna-spartansex-spermax-id-01",
  "/monmusu-quest-side-story-succubus-illusion-id-01",
  "/fella-hame-lips-id-01",
  "/elfen-laid-id-01",
  "/300-en-no-otsukiai-anime-edition-2025-id-01",
  "/depravity-destruction-of-a-female-teacher-id-01",
  "/rin-x-sen-ran-sem-cross-mix-id-01",
  "/birei-okami-mie-id-01",
  "/its-a-family-affair-id-01",
  "/mesu-kyoushi-4-kegasareta-kyoudan-id-01",
  "/imouto-paradise-id-01",
  "/yokujou-bazooka-the-animation-id-01",
  "/oni-chichi-2-id-01",
  "/pakomane-watashi-kyou-kara-meimon-yakyuubu-no-seishorigakari-ni-narimasu-the-animation-id-01",
  "/choukou-sennin-haruka-id-01",
  "/nocturnal-id-01",
  "/delivery-chinko-o-tanomitai-onee-san-id-01",
  "/sinisistar-id-01",
  "/please-rape-me-id-01",
  "/dark-love-id-01",
  "/oni-chichi-kakeeshon-id-01",
  "/yuusha-chan-no-bouken-wa-owatteshimatta-id-01",
  "/tinderbox-id-01",
  "/naedoko-demons-ground-id-01",
  "/mokemoke-taishou-dendou-musume-arisa-id-01",
  "/kokuhaku-ijime-namaiki-douji-gal-no-uragawa-id-01",
  "/love-2-quad-id-01",
  "/so-low-id-01",
  "/harem-time-the-animation-id-01",
  "/sextra-credit-id-01",
  "/jokei-kazoku-inbou-id-01",
  "/gakuen-no-ikenie-id-01",
  "/honoo-no-haramase-motto-hatsuiku-karada-sokutei-2-id-01",
  "/immorality-id-01",
  "/nuki-doki-tenshi-to-akuma-no-sakusei-battle-revolution-id-01",
  "/otome-domain-the-animation-id-01",
  "/gomu-wo-tsukete-to-iimashita-yo-ne-id-01",
  "/sei-yariman-sisters-pakopako-nikki-the-animation-id-01",
  "/sf-the-movie-id-01",
  "/dekakute-ecchi-na-ore-no-ane-id-01",
  "/allargando-the-animation-id-01",
  "/oyakodon-oppai-tokumori-bonyuu-tsuyudaku-de-id-01",
  "/sawaranaide-kotesashi-kun-id-01",
  "/suki-de-suki-de-suki-de-the-animation-id-01",
  "/koukai-benjo-the-animation-id-01",
  "/otome-wa-boku-ni-koishiteru-trinkle-stars-the-animation-id-01",
  "/kohakuiro-no-hunter-the-animation-id-01",
  "/muramata-san-no-himitsu-id-01",
  "/aku-no-onna-kanbu-full-moon-night-id-01",
  "/the-venus-files-id-01",
  "/shabura-rental-id-01",
  "/mahou-shoujo-noble-rose-the-animation-id-01",
  "/princess-69-midnight-gymnastics-id-01",
  "/koiito-kinenbi-the-animation-id-01",
  "/marshmallow-imouto-succubus-id-01",
  "/zton-jingai-animation-a-beautiful-greed-nulu-nulu-id-01",
  "/kara-no-shoujo-id-01",
  "/imouto-wa-gal-kawaii-id-01",
  "/aerobitch-id-01",
  "/creamy-pie-id-01",
  "/mihitsu-no-koi-id-01",
  "/kimi-ga-suki-the-animation-id-01",
  "/yareruko-densha-ecchi-id-01",
  "/yarakashi-id-01",
  "/ruins-seeker-id-01",
  "/meguru-love-id-01",
  "/kyonyuu-fantasy-id-01",
  "/katekano-idol-sister-id-01",
  "/do-s-na-maina-kaichou-sama-ga-m-note-ni-shihai-saremashita-id-01",
  "/oppai-infinity-the-animation-id-01",
  "/haji-shinchishin-id-01",
  "/new-glass-the-movie-id-01",
  "/hasande-ageru-id-01",
  "/ecchi-experience-at-the-shrine-theta-id-01",
  "/tentacle-and-witches-id-01",
  "/demon-busters-ecchi-na-ecchi-na-demon-taiji-the-animation-id-01",
  "/oni-chichi-2-revenge-id-01",
  "/eralin-and-meralin-id-01",
  "/wicked-lessons-id-01",
  "/zettai-junshu-kyousei-kozukuri-kyokashou-id-01",
  "/maid-in-heaven-supers-id-01",
  "/enkou-shoujo-rikujoubu-yukki-no-baai-the-animation-id-01",
  "/liru-wolf-girl-with-you-id-01",
  "/oide-yo-mizuryuu-kei-land-id-01",
  "/lovely-heart-id-01",
  "/shinkyoku-no-grimoire-the-animation-id-01",
  "/kami-machi-sana-chan-the-animation-id-01",
  "/night-shift-nurses-kranke-id-01",
  "/menhera-ayuri-no-yamanai-onedari-headphone-wa-hazusenai-id-01",
  "/oyako-rankan-the-animation-id-01",
  "/madonna-kanjuku-body-collection-id-01",
  "/flashback-game-id-01",
  "/yoasobi-gurashi-id-01",
  "/energy-kyouka-id-01",
  "/elf-no-oshiego-to-sensei-id-01",
  "/sei-brunehilde-gakuen-shoujo-kishidan-to-junpaku-no-panty-the-animation-id-01",
  "/kansen-5-the-daybreak-id-01",
  "/fuurinkanzan-id-01",
  "/shin-sei-yariman-gakuen-enkou-nikki-the-animation-id-01",
  "/kiss-hug-id-01",
  "/virtual-lust-neva-id-01",
  "/shiawase-nara-niku-wo-morou-the-animation-id-01",
  "/nee-summer-id-01",
  "/pure-idol-2-moaning-in-pain-doing-the-splits-id-01",
  "/maken-no-hime-wa-ero-ero-desu-id-01",
  "/maki-chan-to-now-id-01",
  "/yagami-yuu-id-01",
  "/discipline-the-hentai-academy-id-01",
  "/succubus-connect-id-01",
  "/overfuck-overwatch-hentai-id-01",
  "/seikoujo-haitoku-no-biden-dorei-id-01",
  "/pet-life-id-01",
  "/marriage-blue-id-01",
  "/shinsei-kourin-dacryon-luna-id-01",
  "/anejiru-2-the-animation-shirakawa-shimai-ni-omakase-id-01",
  "/mori-no-kuma-san-toumin-chuu-id-01",
  "/nerawareta-megami-tenshi-angeltia-mamotta-ningentachi-ni-uragirarete-id-01",
  "/chu-shite-agechau-oshikake-oneesan-no-seikou-chiryou-id-01",
  "/victorian-maid-maria-no-houshi-id-01",
  "/toumei-ningen-id-01",
  "/moe-love-id-01",
  "/taimanin-yukikaze-id-01",
  "/tsf-monogatari-id-01",
  "/honoo-no-haramase-paidol-my-star-gakuen-z-the-animation-id-01",
  "/lo-re-pako-sukusuku-mizuki-chan-the-animation-id-01",
  "/shounen-ga-otona-ni-natta-natsu-id-01",
  "/yobai-suru-shichinin-no-harame-id-01",
  "/3-byougo-yajuu-goukon-de-sumi-ni-ita-kare-wa-midara-nikushoku-deshita-id-01",
  "/ikenai-koto-the-animation-id-01",
  "/hana-no-joshi-announcer-newscaster-etsuko-id-01",
  "/ryoujoku-famiresu-choukyou-menu-id-01",
  "/oni-chichi-rebuild-id-01",
  "/secret-of-beauty-id-01",
  "/the-blackmail-2-the-animation-id-01",
  "/jimihen-jimiko-wo-kaechau-jun-isei-kouyuu-id-01",
  "/sisters-the-last-day-of-summer-id-01",
  "/kanojo-face-the-animation-id-01",
  "/kafun-shoujo-chuuihou-the-animation-id-01",
  "/kurai-mirai-id-01",
  "/hot-for-teacher-id-01",
  "/helter-skelter-hakudaku-no-mura-id-01",
  "/alice-in-dreamland-id-01",
  "/yuuguu-settai-kotou-no-gokuraku-e-youkoso-id-01",
  "/oni-chichi-id-01",
  "/step-sister-id-01",
  "/oni-chichi-re-born-id-01",
  "/the-blackmail-tomorrow-never-ends-id-01",
  "/gakuen-shinshoku-xx-of-the-dead-id-01",
  "/bloods-inraku-no-ketsuzoku-2-id-01",
  "/midnight-sleazy-train-2-id-01",
  "/joshikousei-no-koshitsuki-id-01",
  "/rei-zero-id-01",
  "/kanojo-ga-mimai-ni-konai-wake-id-01",
  "/ane-koi-suki-kirai-daisuki-id-01",
  "/rakuen-shinshoku-island-of-the-dead-id-01",
  "/chains-of-lust-id-01",
  "/hataraku-otona-no-renai-jijou-the-animation-id-01",
  "/mesu-nochi-torare-id-01",
  "/kimihagu-id-01",
  "/tokubetsu-byoutou-id-01",
  "/love-es-m-the-animation-id-01",
  "/ringetsu-the-animation-id-01",
  "/anata-no-shiranai-kangofu-seiteki-byoutou-24-ji-id-01",
  "/oshiete-re-maid-id-01",
  "/miboujin-nikki-akogare-no-ano-hito-to-hitotsu-yane-no-shita-id-01",
  "/reginetta-san-no-bouken-id-01",
  "/aneki-no-kounai-kaikinbi-id-01",
  "/bakunyuu-bomb-id-01",
  "/words-worth-id-01",
  "/haramaseya-the-animation-id-01",
  "/kagirohi-shaku-kei-another-id-01",
  "/watashi-no-shiranai-mesu-no-kao-id-01",
  "/school-of-bondage-id-01",
  "/hontou-ni-atta-id-01",
  "/aikagi-the-animation-id-01",
  "/jokei-kazoku-iii-himitsu-id-01",
  "/futari-no-aniyome-id-01",
  "/aki-sora-id-01",
  "/tennen-koi-iro-alcohol-id-01",
  "/temptation-id-01",
  "/cosplay-change-pure-kei-joshida-id-1isei-no-kiken-na-seiheki-id-01",
  "/ryou-seibai-gakuen-bishoujo-seisai-hiroku-id-01",
  "/slutty-princess-diaries-id-01",
  "/oni-chichi-2-harvest-id-01",
  "/ichinen-buri-no-the-animation-2025-id-01",
  "/imouto-and-the-too-lewd-temptation-id-01",
  "/mecha-gishi-resta-no-daibouken-id-01",
  "/hana-to-hebi-the-animation-id-01",
  "/swing-out-sisters-id-01",
  "/immoral-sisters-2-id-01",
  "/sei-shoujo-the-animation-id-01",
  "/hump-bang-id-01",
  "/shoujo-kara-shoujo-e-id-01",
  "/ai-no-katachi-ecchi-na-onnanoko-wa-kirai-desu-ka-id-01",
  "/futari-no-yume-mochi-id-01",
  "/paizuri-cheerleader-vs-sakunyuu-ouendan-id-01",
  "/hatsu-inu-2-the-animation-strange-kind-of-woman-again-id-01",
  "/wife-eater-id-01",
  "/sailor-fuku-shinryou-tsumaka-id-01",
  "/yatara-yarashii-fukami-kun-id-01",
  "/spocon-id-01",
  "/menkui-id-01",
  "/iyashite-agerun-saiyuuki-id-01",
  "/sexfriend-no-senpai-the-animation-id-01",
  "/super-naughty-maid-id-01",
  "/himekishi-lilia-id-01",
  "/niku-mesu-r30-nikuyoku-ni-ochita-mesu-tachi-the-animation-id-01",
  "/tsugou-no-yoi-sexfriend-id-01",
  "/rape-rape-rape-id-01",
  "/behind-closed-doors-id-01",
  "/tsun-tsun-maid-wa-ero-ero-desu-id-01",
  "/demonion-gaiden-id-01",
  "/rin-x-sen-hakudaku-onna-kyoushi-to-yaroudomo-id-01",
  "/shusaku-replay-id-01",
  "/inshitsu-otaku-ni-ikareru-kanojo-id-01",
  "/dyogrammaton-id-01",
  "/debt-sisters-id-01",
  "/chikan-monogatari-id-01",
  "/desperate-carnal-housewives-id-01",
  "/constraint-copulation-id-01",
  "/aku-no-onna-kanbu-id-01",
  "/lingeries-id-01",
  "/my-imouto-koakuma-na-a-cup-id-01",
  "/inyouchuu-shoku-ryoushokutou-taimaroku-id-01",
  "/osananajimi-to-doukyuusei-id-01",
  "/dark-blue-id-01",
  "/immoral-sisters-3-id-01",
  "/hishoka-drop-the-animation-id-01",
  "/tsunpuri-id-01",
  "/slave-nurses-id-01",
  "/okusama-wa-michael-id-01",
  "/i-can-id-01",
  "/dont-frozen-hentai-id-01",
  "/seihou-shouka-saint-lime-id-01",
  "/fukubiki-triangle-futaba-wa-atafuta-id-01",
  "/rensa-byoutou-id-01",
  "/renketsu-houshiki-id-01",
  "/immoral-sisters-id-01",
  "/mahou-shoujo-elena-id-01",
  "/taimanin-asagi-id-01",
  "/angel-blade-punish-id-01",
  "/peace-hame-id-01",
  "/namanaka-hyaku-percent-katamusubi-no-shinpa-id-01",
  "/bible-black-gaiden-id-01",
  "/futsuma-shoujo-charlotte-id-01",
  "/secret-desires-id-01",
  "/ran-sem-hakudaku-delmo-tsuma-no-miira-tori-id-01",
  "/ane-haramix-id-01",
  "/mitasarete-mezameru-asa-ni-jimi-na-choushoku-wo-the-animation-id-01",
  "/machi-gurumi-no-wana-hakudaku-ni-mamireta-shitai-id-01",
  "/black-gate-kanin-no-gakuen-id-01",
  "/tenioha-onnanoko-datte-honto-wa-ecchi-da-yo-id-01",
  "/mitama-nin-id-01",
  "/kisaku-spirit-the-letch-lives-id-01",
  "/heartwork-symphony-of-destruction-id-01",
  "/mizugi-kanojo-the-animation-id-01",
  "/tensei-kendo-no-harem-colosseum-id-01",
  "/kangoku-senkan-id-01",
  "/boku-to-nurse-no-kenshuu-nisshi-the-animation-id-01",
  "/doukyo-suru-neneki-id-01",
  "/a-time-to-screw-toki-neiro-id-01",
  "/shinsei-futanari-idol-dekatama-kei-id-01",
  "/pretty-x-cation-the-animation-id-01",
  "/secret-journey-id-01",
  "/meijyou-id-01",
  "/kansen-2-inzai-toshi-id-01",
  "/kyuuketsuki-id-01",
  "/soushisouai-note-the-animation-id-01",
  "/elf-hime-nina-id-01",
  "/the-story-of-little-monica-id-01",
  "/ore-wa-kanojo-wo-shinjiteru-id-01",
  "/bondage-101-id-01",
  "/yabai-fukushuu-yami-site-id-01",
  "/ijou-chitai-jikken-dorei-id-01",
  "/maison-plaisir-id-01",
  "/kuraibito-id-01",
  "/colosseum-no-senki-another-story-id-01",
  "/cafe-junkie-id-01",
  "/after-school-mania-club-id-01",
  "/yume-kui-tsurumiku-shiki-game-seisaku-id-01",
  "/betsu-ni-anta-no-tame-ni-ookiku-nattan-janain-dakara-ne-id-01",
  "/ojou-sama-yomeiri-kousou-id-01",
  "/shoujo-senki-brain-jacker-id-01",
  "/shiiba-san-no-ura-no-kao-with-imouto-lip-id-01",
  "/netorare-tanabe-yuuka-no-dokuhaku-id-01",
  "/maple-colors-id-01",
  "/last-waltz-hakudaku-mamire-no-natsu-gasshuku-id-01",
  "/ikusa-otome-valkyrie-2-id-01",
  "/stringendo-angel-tachi-no-private-lesson-id-01",
  "/haramasete-seiryuu-kun-id-01",
  "/ore-no-yubi-de-midarero-heitengo-futarikiri-no-salon-de-id-01",
  "/lovely-day-boku-to-kanojo-no-nana-nichikan-id-01",
  "/boin-id-01",
  "/busou-shoujotai-blade-briders-the-animation-id-01",
  "/soshite-watashi-wa-ojisan-ni-id-01",
  "/shusaku-liberty-id-01",
  "/hitoriga-the-animation-id-01",
  "/wet-summer-days-id-01",
  "/jk-to-orc-heidan-aku-buta-oni-ni-ryougyaku-sareta-seijo-gakuen-id-01",
  "/inda-no-himekishi-janne-id-01",
  "/living-sex-toy-delivery-id-01",
  "/the-erotic-temptress-id-01",
  "/kitsune-musume-no-ecchi-oyado-id-01",
  "/furifure-2-id-01",
  "/kiken-na-mori-onigokko-id-01",
  "/wana-hakudaku-mamire-no-houkago-id-01",
  "/sora-no-iro-mizu-no-iro-id-01",
  "/beat-angel-escalayer-id-01",
  "/bondage-game-shinsou-no-reijoutachi-id-01",
  "/school-id-01",
  "/hell-knight-ingrid-id-01",
  "/sex-craft-id-01",
  "/princess-knight-catue-id-01",
  "/shoukoujo-the-animation-id-01",
  "/kiriya-hakushaku-ke-no-roku-shimai-id-01",
  "/soukou-kijo-iris-id-01",
  "/kyonyuu-try-tanki-shuuchuu-chichi-momi-lesson-id-01",
  "/night-shift-nurses-2-id-01",
  "/oppai-gakuen-marching-band-bu-id-01",
  "/ryuusei-tenshi-primaveil-id-01",
  "/princess-lover-id-01",
  "/bakunyuu-maid-kari-id-01",
  "/girls-rush-the-animation-id-01",
  "/natsumushi-the-animation-id-01",
  "/hitou-meguri-kakure-yu-id-01",
  "/fuufu-koukan-modorenai-yoru-id-01",
  "/oppai-heart-kanojo-wa-kedamono-hatsujouki-id-01",
  "/yokorenbo-immoral-mother-id-01",
  "/usamimi-bouken-tan-sekuhara-shinagara-sekai-wo-sukue-id-01",
  "/sex-warrior-pudding-id-01",
  "/ojousama-wa-h-ga-osuki-the-animation-id-01",
  "/mesu-wo-karu-mura-id-01",
  "/sex-ward-id-01",
  "/house-of-5-lusts-id-01",
  "/fechikano-id-01",
  "/idol-kouhosei-id-01",
  "/hyoudou-ibuki-id-01",
  "/otome-chibaku-yuugi-id-01",
  "/momoiro-milk-id-01",
  "/korashime-2-kyouikuteki-depaga-shidou-id-01",
  "/tropical-kiss-id-01",
  "/pandra-the-animation-shiroki-yokubou-kuro-no-kibou-id-01",
  "/ikusa-otome-valkyrie-g-id-01",
  "/amakano-id-01",
  "/the-two-facials-of-eve-id-01",
  "/honoo-no-haramase-tenkousei-id-01",
  "/snow-night-stories-id-01",
  "/binkan-athlete-id-01",
  "/jiburiru-the-devil-angel-id-01",
  "/kegareboshi-id-01",
  "/rinkan-gakuen-yamete-okaasan-minaide-id-01",
  "/15-bishoujo-hyouryuuki-id-01",
  "/dorei-usagi-to-anthony-the-animation-id-01",
  "/discipline-zero-id-01",
  "/nanase-ren-id-01",
  "/naisho-no-wakana-san-id-01",
  "/shoujo-x-shoujo-x-shoujo-the-animation-id-01",
  "/cosplay-roshutsu-kenkyuukai-id-01",
  "/imouto-twins-id-01",
  "/mikagura-detective-agency-id-01",
  "/ikusa-otome-valkyrie-id-01",
  "/bioshag-trinity-id-01",
  "/yubisaki-annainin-shirudaku-settai-okawari-sanhaime-id-01",
  "/showtime-uta-no-oneesan-datte-shitai-id-01",
  "/asa-kara-zusshiri-milk-pot-id-01",
  "/seitokaichou-hikaru-id-01",
  "/forbidden-love-id-01",
  "/houkago-nyannyan-id-01",
  "/kaede-to-suzu-the-animation-id-01",
  "/kawarazaki-ke-no-ichizoku-2-id-01",
  "/fault-id-01",
  "/anejiru-the-animation-shirakawa-sanshimai-ni-omakase-id-01",
  "/qualiaffordance-id-01",
  "/secret-mission-sennyuu-sousakan-wa-zettai-ni-makenai-id-01",
  "/tayu-tayu-id-01",
  "/spa-of-love-id-01",
  "/fighting-of-ecstasy-id-01",
  "/shocking-pink-id-01",
  "/takarasagashi-no-natsuyasumi-id-01",
  "/the-harvest-night-id-01",
  "/injuu-gakuen-la-blue-girl-id-01",
  "/lovely-x-cation-the-animation-id-01",
  "/night-shift-nurses-id-01",
  "/shin-ringetsu-id-01",
  "/legend-of-the-wolf-woman-id-01",
  "/magical-witch-academy-boku-to-sensei-no-magical-lesson-the-animation-id-01",
  "/toriko-hime-hakudaku-mamire-no-reijou-id-01",
  "/samurai-hormone-the-animation-id-01",
  "/akiba-girls-id-01",
  "/discode-ijou-seiai-id-01",
  "/immoral-id-01",
  "/eromame-id-01",
  "/cosplay-rakuen-id-01",
  "/dark-shell-lust-in-the-cage-id-01",
  "/shujii-no-inbou-id-01",
  "/magical-girl-isuka-id-01",
  "/body-transfer-id-01",
  "/accelerando-datenshi-tachi-no-sasayaki-id-01",
  "/anata-dake-konbanwa-id-01",
  "/ikusa-otome-suvia-id-01",
  "/nozoki-ana-id-01",
  "/stringendoaccelerando-ultimatum-sera-id-01",
  "/alignment-you-you-the-animation-id-01",
  "/mark-your-kiss-the-animation-id-01",
  "/momoiro-bouenkyou-anime-edition-id-01",
  "/nee-chanto-shiyou-yo-id-01",
  "/chinetsu-karte-the-devilish-cherry-id-01",
  "/ayatsuri-haramase-dreamnote-id-01",
  "/daiakuji-the-xena-buster-id-01",
  "/perverted-thomas-id-01",
  "/shinshou-genmukan-id-01",
  "/nuki-doki-tenshi-to-akuma-no-sakusei-battle-id-01",
  "/bi-chiku-beach-nangoku-nyuujoku-satsueikai-id-01",
  "/kore-tte-naani-id-01",
  "/black-widow-id-01",
  "/manin-densha-id-01",
  "/seikou-lose-a-virgin-for-the-first-term-id-01",
  "/perverse-investigations-id-01",
  "/naughty-nurses-id-01",
  "/kininaru-roommate-id-01",
  "/stretta-the-animation-id-01",
  "/true-blue-id-01",
  "/angel-core-tenshi-tachi-no-sumika-id-01",
  "/shusaku-id-01",
  "/amai-choubatsu-watashi-wa-kanshu-senyou-pet-id-01",
  "/cool-devices-id-01",
  "/fault-service-aratanaru-rival-id-01",
  "/sibling-secret-shes-the-twisted-sister-id-01",
  "/slaves-to-passion-id-01",
  "/sexy-sailor-soldiers-id-01",
  "/reunion-id-01",
  "/hakoiri-shoujo-virgin-territory-id-01",
  "/kansen-inyoku-no-rensa-id-01",
  "/samayou-midara-na-lunatics-id-01",
  "/anehame-ore-no-hatsukoi-ga-jisshi-na-wake-ga-nai-id-01",
  "/rxxx-prescription-for-pain-id-01",
  "/the-boundary-between-dream-and-reality-id-01",
  "/dorei-maid-princess-id-01",
  "/darling-id-01",
  "/bride-of-rakuin-id-01",
  "/kateikyoushi-no-oneesan-2-the-animation-h-no-hensachi-agechaimasu-id-01",
  "/shinjin-tour-conductor-id-01",
  "/hatsu-inu-the-animation-id-01",
  "/shishunki-no-obenkyou-id-01",
  "/love-colon-id-01",
  "/slave-market-id-01",
  "/etsuraku-no-tane-the-animation-id-01",
  "/angel-blade-id-01",
  "/grope-yami-no-naka-no-kotori-tachi-id-01",
  "/sexfriend-id-01",
  "/jiburiru-the-devil-angel-3-id-01",
  "/kojin-jugyou-the-animation-schoolgirl-ready-for-a-private-lesson-id-01",
  "/chikan-juunintai-the-animation-id-01",
  "/moonlight-lady-id-01",
  "/milky-maid-id-01",
  "/inmu-gakuen-inmu-ni-torawareta-bijin-shimai-id-01",
  "/wizard-girl-ambitious-id-01",
  "/zero-sum-game-id-01",
  "/seme-chichi-id-01",
  "/d-spray-id-01",
  "/mija-beautifull-demon-id-01",
  "/oshaburi-announcer-id-01",
  "/luv-wave-id-01",
  "/gakuen-2-id-01",
  "/shin-kyouhaku-2-the-animation-kizu-ni-saku-hana-senketsu-no-kurenai-id-01",
  "/hitozuma-cosplay-kissa-2-hitozuma-lovelove-cosplay-ova-id-01",
  "/issho-ni-ecchi-id-01",
  "/seifuku-shojo-the-animation-id-01",
  "/samurai-xxx-id-01",
  "/sexy-fighter-manami-id-01",
  "/lesbian-ward-id-01",
  "/ero-manga-mitai-na-koi-shiyo-id-01",
  "/furifure-the-animation-id-01",
  "/la-blue-girl-returns-id-01",
  "/harumi-chan-no-oita-2025-id-01",
  "/fukubiki-triangle-miharu-after-id-01",
  "/yufin-to-ecchi-id-01",
  "/hardcore-hospital-id-01",
  "/maid-ane-id-01",
  "/internal-medicine-id-01",
  "/true-blue-gaiden-id-01",
  "/gakuen-shimai-id-01",
  "/ikusa-otome-suvia-bonus-video-id-01",
  "/xl-joushi-id-01",
  "/in-series-in-goku-koushuu-rinkan-id-01",
  "/blood-shadow-id-01",
  "/otome-juurin-yuugi-maiden-infringement-play-id-01",
  "/dirty-laundry-id-01",
  "/koikishi-purely-kiss-the-animation-id-01",
  "/rescue-me-id-01",
  "/bible-black-imari-rape-scene-id-01",
  "/aki-sora-yume-no-naka-id-01",
  "/flutter-of-birds-ii-tenshi-tachi-no-tsubasa-id-01",
  "/haitoku-no-shoujo-id-01",
  "/crimson-climax-id-01",
  "/blood-royale-id-01",
  "/the-last-kunoichi-id-01",
  "/swallowtail-inn-id-01",
  "/cage-id-01",
  "/imouto-paradise-2-id-01",
  "/bad-end-id-01",
  "/fairy-in-the-forest-id-01",
  "/holy-virgins-id-01",
  "/ichigo-aika-zatsu-de-namaiki-na-imouto-to-warikirenai-ani-id-01",
  "/xpress-train-id-01",
  "/harley-quinn-hentai-id-01",
  "/mouryou-no-nie-id-01",
  "/t-love-id-01",
  "/jk-to-ero-giin-sensei-id-01",
  "/rennyuu-tales-the-animation-id-01",
  "/queen-and-slave-id-01",
  "/inmu-feast-of-victims-id-01",
  "/gitai-saimin-id-01",
  "/darcrows-id-01",
  "/triangle-blue-id-01",
  "/inyoku-tokkyuu-zetsurinou-id-01",
  "/inma-seiden-the-legend-of-the-beast-of-lust-id-01",
  "/submission-central-id-01",
  "/yosino-mura-id-01",
  "/beast-city-id-01",
  "/yubisaki-kara-honki-no-netsujou-osananajimi-wa-shouboushi-id-01",
  "/the-urotsuki-id-01",
  "/kagirohi-shaku-kei-id-01",
  "/cream-lemon-id-01",
  "/valkyrie-choukyou-semen-tank-no-ikusa-otome-10-nin-shimai-id-01",
  "/souryo-to-majiwaru-shikiyoku-no-yoru-ni-id-01",
  "/ona-x2-id-01",
  "/hika-ryoujoku-the-lust-of-shame-id-01",
  "/love-selection-the-animation-id-01",
  "/elf-no-futagohime-willan-to-arsura-id-01",
  "/shuumatsu-hospital-id-01",
  "/brandish-id-01",
  "/hitozuma-cosplay-kissa-id-01",
  "/ikusa-otome-valkyrie-shinshou-id-01",
  "/shuudengo-capsule-hotel-de-joushi-ni-binetsu-tsutawaru-yoru-id-01",
  "/araiya-san-ore-to-aitsu-ga-onnayu-de-id-01",
  "/binetsukko-b37c-id-01",
  "/yama-hime-no-hana-id-01",
  "/kagaku-na-yatsura-id-01",
  "/koihime-id-01",
  "/natsu-to-hako-id-01",
  "/kotowari-kimi-no-kokoro-no-koboreta-kakera-id-01",
  "/virgin-auction-id-01",
  "/class-reunion-again-id-01",
  "/innocent-blue-id-01",
  "/shitai-wo-arau-id-01",
  "/private-emotion-id-01",
  "/akina-to-onsen-de-h-shiyo-id-01",
  "/dark-id-01",
  "/sin-sorority-id-01",
  "/omiai-aite-wa-oshiego-tsuyoki-na-mondaiji-id-01",
  "/miyazaki-maya-daizukan-id-01",
  "/sazanami-soushi-ni-junketsu-wo-sasagu-id-01",
  "/masaru-ashita-no-yukinojou-2-id-01",
  "/tokumu-sousakan-rei-fuko-id-01",
  "/toriko-no-chigiri-id-01",
  "/chu2-id-01",
  "/floating-material-id-01",
  "/houkago-2-the-animation-id-01",
  "/inyutsu-no-yakata-the-animation-id-01",
  "/jk-to-inkou-kyoushi-4-id-01",
  "/junai-maniac-id-01",
  "/eternity-shinya-no-nurekoi-channel-id-01",
  "/city-of-sin-id-01",
  "/at-zanarkand-id-01",
  "/sono-hanabira-ni-kuchizuke-wo-reo-x-mai-diaries-id-01",
  "/ail-maniax-inma-seifukugari-majogari-no-yoru-ni-id-01",
  "/magical-canan-id-01",
  "/my-mysterious-girlfriend-id-01",
  "/enzai-id-01",
  "/25-sai-no-joshikousei-id-01",
  "/innocent-shoujo-memoria-id-01",
  "/romance-is-in-the-flash-of-the-sword-ii-id-01",
  "/hininden-gausu-id-01",
  "/f3-frantic-frustrated-female-id-01",
  "/mei-king-id-01",
  "/oni-tensei-id-01",
  "/kowaremono-fragile-hearts-id-01",
  "/shino-sensei-no-yuuwaku-jugyou-id-01",
  "/tokyo-requiem-id-01",
  "/chicchana-onaka-id-01",
  "/private-sessions-2-id-01",
  "/nurse-me-id-01",
  "/doukyuusei-id-01",
  "/onna-kyoushi-nijuusan-sai-id-01",
  "/bride-of-the-goblin-id-01",
  "/school-girl-special-lesson-id-01",
  "/bride-of-darkness-id-01",
  "/zero-no-mono-id-01",
  "/seein-ao-id-01",
  "/girl-next-door-id-01",
  "/sex-taxi-id-01",
  "/night-tail-id-01",
  "/professor-pain-id-01",
  "/urotsukidoji-legend-of-the-overfiend-id-01",
  "/shiofuki-mermaid-id-01",
  "/pure-mail-id-01",
  "/ateuma-chara-no-kuse-shite-supadari-ouji-ni-chouai-sarete-imasu-id-01",
  "/tokio-private-police-id-01",
  "/concerto-id-01",
  "/star-jewel-id-01",
  "/choujin-densetsu-urotsukidouji-3-id-01",
  "/blind-night-id-01",
  "/ward-of-original-sin-id-01",
  "/angels-in-the-court-id-01",
  "/mahou-shoujo-sae-id-01",
  "/cartagra-tsuki-gurui-no-yamai-id-01",
  "/otona-nya-koi-no-shikata-ga-wakaranee-id-01",
  "/itoshi-no-kotodama-id-01",
  "/skirt-no-naka-wa-kedamono-deshita-id-01",
  "/tsuki-kagerou-id-01",
  "/onmyouji-youen-emaki-id-01",
  "/teachers-pet-2-id-01",
  "/shoujo-senki-soul-eater-id-01",
  "/shishunki-shoujo-id-01",
  "/fujun-isei-kouyuu-taisetsu-na-kimi-e-id-01",
  "/milk-money-id-01",
  "/dna-hunter-id-01",
  "/asgaldh-the-distortion-testament-id-01",
  "/custom-slave-id-01",
  "/lets-arbeit-id-01",
  "/kakyuusei-2-anthology-id-01",
  "/houkago-2-sayuri-id-01",
  "/inko-id-01",
  "/shounen-maid-kuuro-kun-tenshi-no-uta-id-01",
  "/hyakkiyakou-warashi-id-01",
  "/kage-id-01",
  "/the-bizarre-cage-id-01",
  "/love-is-the-number-of-keys-id-01",
  "/buta-no-gotoki-sanzoku-ni-torawarete-shojo-wo-ubawareru-kyonyuu-himekishi-onna-senshi-id-01",
  "/otokonoko-delivery-id-01",
  "/soushitsukyou-id-01",
  "/gorimaccho-to-bloomers-lesson-id-01",
  "/i-love-you-id-01",
  "/issunboushi-id-01",
  "/mahou-senshi-sweet-knights-heroine-ryoujoku-shirei-id-01",
  "/spy-of-darkness-id-01",
  "/scourge-of-the-evil-id-01",
  "/binetsu-hime-zange-no-shou-id-01",
  "/jii-tousaku-id-01",
  "/namaiki-kissuisou-e-youkoso-the-animation-id-01",
  "/gakuen-maria-bakunyuu-teachers-id-01",
  "/vicious-id-01",
  "/reijou-caster-ingyaku-no-wana-id-01",
  "/another-lady-innocent-id-01",
  "/ryoujoku-guerrilla-kari-3-id-01",
  "/papa-datte-shitai-id-01",
  "/the-elven-bride-id-01",
  "/chijoku-kankin-id-01",
  "/love-doll-id-01",
  "/kussetsu-id-01",
  "/wind-of-ebenbourg-id-01",
  "/beyond-id-01",
  "/kunoichi-gakuen-ninpouchou-id-01",
  "/inyouchuu-the-animation-id-01",
  "/shion-id-01",
  "/lewd-room-id-01",
  "/inyouchuu-shoku-harami-ochiru-shoujo-tachi-anime-edition-id-01",
  "/harukoi-otome-id-01",
  "/venus-blood-brave-id-01",
  "/chimera-target-i-datenshi-kourin-id-01",
  "/crimson-girls-chikan-shihai-id-01",
  "/hot-juicy-teacher-id-01",
  "/isaku-respect-id-01",
  "/saimin-ryoujoku-gakuen-id-01",
  "/hime-dorei-id-01",
  "/alien-from-the-darkness-id-01",
  "/scold-with-dirty-words-id-01",
  "/choujin-densetsu-urotsukidouji-5-kanketsu-hen-id-01",
  "/newmanoid-cam-cam-castin-id-01",
  "/auction-bijo-dorei-id-01",
  "/class-reunion-yesterday-once-more-id-01",
  "/choujin-densetsu-urotsukidouji-inferno-road-id-01",
  "/uchuu-kaizoku-sara-id-01",
  "/women-at-work-id-01",
  "/gosenzo-sane-id-01",
  "/princess-69-id-01",
  "/cool-de-m-id-01",
  "/junk-land-the-animation-id-01",
  "/izumo-id-01",
  "/sexy-magical-girl-ai-id-01",
  "/kisaku-id-01",
  "/shin-ruri-iro-no-yuki-id-01",
  "/deep-voice-id-01",
  "/ecchies-id-01",
  "/warau-kangofu-the-animation-id-01",
  "/shitsurakuen-id-01",
  "/mezzo-forte-id-01",
  "/kugutsu-ai-doura-gaiden-id-01",
  "/daiakuji-the-xena-buster-specials-id-01",
  "/moral-hazard-id-01",
  "/mahou-shoujo-ai-san-the-anime-id-01",
  "/kisaku-the-letch-iii-id-01",
  "/hitou-meguri-the-animation-wakaokami-rachiru-id-01",
  "/mahou-shoujo-wa-kiss-shite-kawaru-id-01",
  "/elfina-yoru-e-to-urareta-oukoku-de-the-animation-id-01",
  "/virgin-night-id-01",
  "/ginga-teikoku-no-metsubou-gaiden-aoki-ookami-tachi-no-densetsu-id-01",
  "/hooligan-quest-for-the-seven-holy-dildos-id-01",
  "/midnight-sleazy-train-id-01",
  "/hi-me-go-to-id-01",
  "/mozu-no-nie-id-01",
  "/kirameki-no-kyoudai-sex-crime-id-01",
  "/kamyla-id-01",
  "/love-machine-animaid-shoufu-23-gou-id-01",
  "/okusama-wa-mahoutsukai-id-01",
  "/a-heat-for-all-seasons-id-01",
  "/hime-sama-gentei-id-01",
  "/tail-of-two-sisters-id-01",
  "/yu-no-id-01",
  "/a-forbidden-time-id-01",
  "/injuu-daikessen-id-01",
  "/elle-id-01",
  "/youshou-id-01",
  "/kimi-no-na-wo-yobeba-id-01",
  "/kateikyoushi-no-oneesan-the-animation-h-no-hensachi-agechaimasu-id-01",
  "/tsun-m-gyutto-shibatte-shidoushite-the-animation-id-01",
  "/teachers-pet-id-01",
  "/keibiin-id-01",
  "/angels-in-the-court-2-id-01",
  "/angelium-id-01",
  "/karen-id-01",
  "/countdown-to-delight-id-01",
  "/doukyuusei-2-id-01",
  "/zecchou-rocket-id-01",
  "/kite-id-01",
  "/dollhouse-id-01",
  "/g-taste-id-01",
  "/kunoichi-sakuya-id-01",
  "/stairs-houkago-no-album-id-01",
  "/kama-sutra-id-01",
  "/oyasumi-sex-2025-id-01",
  "/arisugawa-ren-tte-honto-wa-onna-nanda-yo-ne-id-01",
  "/showtime-uta-no-oneesan-datte-shitai-2-id-01",
  "/words-worth-gaiden-id-01",
  "/kanin-tokkyuu-michishio-id-01",
  "/five-card-id-01",
  "/orchid-emblem-id-01",
  "/super-sexy-android-id-01",
  "/yubisaki-kara-honki-no-netsujou-2-koibito-wa-shouboushi-id-01",
  "/kawarazaki-ke-no-ichizoku-the-animation-id-01",
  "/cambrian-id-01",
  "/milkyway-id-01",
  "/private-sessions-id-01",
  "/diabolus-kikoku-id-01",
  "/pigeon-blood-id-01",
  "/virgin-touch-id-01",
  "/hyakki-the-secret-of-devils-island-id-01",
  "/ookami-san-wa-taberaretai-id-01",
  "/kurutta-kyoutou-danzai-no-gakuen-id-01",
  "/m-e-m-yogosareta-junketsu-id-01",
  "/magical-twilight-id-01",
  "/alice-doll-id-01",
  "/bondage-mansion-id-01",
  "/magical-moe-id-01",
  "/the-maiden-diaries-id-01",
  "/shojyo-koakuma-kei-the-writhing-women-id-01",
  "/legend-of-the-black-eye-id-01",
  "/lesson-of-darkness-id-01",
  "/natsuyasumi-id-01",
  "/boku-no-pico-id-01",
  "/choisuji-2025-id-01",
  "/angel-of-darkness-id-01",
  "/twin-angels-id-01",
  "/idol-of-darkness-id-01",
  "/dream-hazard-akuma-no-program-id-01",
  "/lady-blue-id-01",
  "/maiden-of-deliverance-id-01",
  "/mahya-the-servant-id-01",
  "/dragon-pink-id-01",
  "/onna-kyoushi-nikutai-jugyou-id-01",
  "/taimanin-asagi-2-id-01",
  "/doura-id-01",
  "/tower-of-etruria-id-01",
  "/isaku-id-01",
  "/otoko-no-ko-ojousama-id-01",
  "/kekkai-id-01",
  "/kijutsushi-x-majutsushi-osaka-tanteibu-no-jikenbo-id-01",
  "/dragon-rider-id-01",
  "/battle-team-lakers-ex-id-01",
  "/endless-serenade-id-01",
  "/princess-holiday-korogaru-ringo-tei-senya-ichiya-id-01",
  "/lunatic-night-id-01",
  "/campus-id-01",
  "/nine-oclock-woman-id-01",
  "/can-can-bunny-id-01",
  "/trick-or-alice-id-01",
  "/love2-police-id-01",
  "/sensitive-pornograph-id-01",
  "/variable-geo-id-01",
  "/twin-dolls-id-01",
  "/castle-fantasia-seima-taisen-id-01",
  "/kakyuusei-2-sketchbook-id-01",
  "/green-green-thirteen-erolutions-id-01",
  "/ashita-no-yukinojou-id-01",
  "/nymphs-of-the-stratosphere-id-01",
  "/shuudan-chikan-densha-id-01",
  "/bondage-house-id-01",
  "/erotic-torture-chamber-id-01",
  "/vixens-id-01",
  "/septem-charm-magical-kanan-sp-summer-camp-id-01",
  "/co-ed-affairs-id-01",
  "/choujin-densetsu-urotsukidouji-2-id-01",
  "/handle-with-care-id-01",
  "/binetsu-yakusoku-no-toki-id-01",
  "/yuuwaku-countdown-id-01",
  "/dragon-knight-4-id-01",
  "/zoku-koihime-id-01",
  "/shokuzai-no-kyoushitsu-id-01",
  "/sins-of-the-flesh-id-01",
  "/stainless-night-id-01",
  "/slight-fever-syndrome-id-01",
  "/buttobi-cpu-id-01",
  "/natural-2-duo-id-01",
  "/gedou-gakuen-id-01",
  "/midnight-panther-id-01",
  "/yarima-queen-id-01",
  "/mahou-shoujo-meruru-id-01",
  "/spaceship-agga-ruter-id-01",
  "/minerva-no-kenshi-id-01",
  "/reinou-tantei-miko-id-01",
  "/doll-saaya-id-01",
  "/momiji-id-01",
  "/jisshuusei-id-01",
  "/you-bishoujo-miruku-chan-id-01",
  "/keraku-no-oh-king-of-pleasure-id-01"
];


export const mockUser = {
  username: "Henpro",
  bio: "Follow us for Daily Sauce!!",
  avatar: "/johi.png",
  design: "design8.jpeg",
};

// =========================================================
// 2. DYNAMIC VISIBILITY CALCULATION
// =========================================================

export function getVisiblePostCount() {
  const INITIAL_REVEAL_DATE_MS = new Date(
    "2025-12-09T23:00:00+05:30"
  ).getTime();
  const REVEAL_RATE = 2; // 2 posts per day
  const INITIAL_POSTS = 2; // Start with 2 posts visible.

  const now = Date.now();
  const timeElapsedMs = now - INITIAL_REVEAL_DATE_MS;

  if (timeElapsedMs < 0) {
    return INITIAL_POSTS;
  }

  const daysElapsed = Math.floor(timeElapsedMs / (1000 * 60 * 60 * 24));

  let visibleCount = INITIAL_POSTS + daysElapsed * REVEAL_RATE;

  return Math.min(visibleCount, originalData.length);
}

// =========================================================
// 3. AD SCRIPTS
// =========================================================

export function getAdScripts() {
  // Note: Vercel may block certain ad scripts or require specific configurations.
  const adScriptTop = `<script async="async" data-cfasync="false" src="//brownrealization.com/917495758f35e40004f3af3fe8c04eb8/invoke.js"></script><div id="container-917495758f35e40004f3af3fe8c04eb8"></div>`;
  const adScriptBottom = `<script async="async" data-cfasync="false" src="//brownrealization.com/33a497c32aa8ecfffc3d4653d57e37f4/invoke.js"></script><div id="container-33a497c32aa8ecfffc3d4653d57e37f4"></div>`;

  return { adScriptTop, adScriptBottom };
}
